FROM ubuntu:latest
RUN apt-get update && apt-get install -y openssh-server openssh-client sshpass

# Cria diretório pro ssh funcionar
RUN mkdir /var/run/sshd

# Mudar senha do root
RUN echo 'root:ubuntu123' | chpasswd

# Permitir conexão ssh como root
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# copiar script para dentro do conteiner
COPY copiar_arquivo.sh /copiar_arquivo.sh

# tornar executável
RUN chmod +x /copiar_arquivo.sh

# Pegar o arquivo do host e copiar para o container, que o copiará para o container do fedora
COPY arquivo.txt /arquivo.txt

EXPOSE 22
CMD ["/bin/bash", "/copiar_arquivo.sh"]

